export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_END = 'SIGNIN_END';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const CHECK_EMAIL_START = 'CHECK_EMAIL_START';
export const CHECK_EMAIL_END = 'CHECK_EMAIL_END';
export const CHECK_EMAIL_SUCCESS = 'CHECK_EMAIL_SUCCESS';
export const CHECK_EMAIL_FAIL = 'CHECK_EMAIL_FAIL';