export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_END = 'SIGNIN_END';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const CHECK_EMAIL_START = 'CHECK_EMAIL_START';
export const CHECK_EMAIL_END = 'CHECK_EMAIL_END';
export const CHECK_EMAIL_SUCCESS = 'CHECK_EMAIL_SUCCESS';
export const CHECK_EMAIL_FAIL = 'CHECK_EMAIL_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_END = 'SIGNUP_END';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const GET_ZONE_LIST_START = 'GET_ZONE_LIST_START';
export const GET_ZONE_LIST_SUCCESS = 'GET_ZONE_LIST_SUCCESS';
export const GET_ZONE_LIST_FAIL = 'GET_ZONE_LIST_FAIL';

export const GET_GCP_ZONES_START = 'GET_GCP_ZONES_START';
export const GET_GCP_ZONES_SUCCESS = 'GET_GCP_ZONES_SUCCESS';
export const GET_GCP_ZONES_FAIL = 'GET_GCP_ZONES_FAIL';

export const CREATE_SCAN_START = 'CREATE_SCAN_START';
export const CREATE_SCAN_SUCCESS = 'CREATE_SCAN_SUCCESS';
export const CREATE_SCAN_FAIL = 'CREATE_SCAN_FAIL';
export const CREATE_SCAN_CLEAR = 'CREATE_SCAN_CLEAR';